// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3iumMH-M18Q1QDAVMbG0SeKoXI4RJ5ss',
    appId: '1:671844106601:web:728dc8626f99690b957df8',
    messagingSenderId: '671844106601',
    projectId: 'library-app-93482',
    authDomain: 'library-app-93482.firebaseapp.com',
    storageBucket: 'library-app-93482.firebasestorage.app',
    measurementId: 'G-BZWGYKLJX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLRC1l2INzqndwVfpDx6F3k7of9bt78GQ',
    appId: '1:671844106601:android:c6a8391ee4e82a7d957df8',
    messagingSenderId: '671844106601',
    projectId: 'library-app-93482',
    storageBucket: 'library-app-93482.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs8oFpCnUwn1b378h7z8SItRq4lU7XG70',
    appId: '1:671844106601:ios:4012f737875a0bb7957df8',
    messagingSenderId: '671844106601',
    projectId: 'library-app-93482',
    storageBucket: 'library-app-93482.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs8oFpCnUwn1b378h7z8SItRq4lU7XG70',
    appId: '1:671844106601:ios:4012f737875a0bb7957df8',
    messagingSenderId: '671844106601',
    projectId: 'library-app-93482',
    storageBucket: 'library-app-93482.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3iumMH-M18Q1QDAVMbG0SeKoXI4RJ5ss',
    appId: '1:671844106601:web:bcf6e87c0d4f9a51957df8',
    messagingSenderId: '671844106601',
    projectId: 'library-app-93482',
    authDomain: 'library-app-93482.firebaseapp.com',
    storageBucket: 'library-app-93482.firebasestorage.app',
    measurementId: 'G-4YDYK7KS24',
  );
}
